%let path1=d:\userdata\Shared\CKD_Endpts\CKD-EPI CT\Data\TRIALNAME;
%let path2=d:\userdata\Shared\CKD_Endpts\CKD-EPI CT\0_Master_SAS_R_programs\1 TxtEffects;

libname Master "&path1";
libname SASdata  "&path1\analysis_sets\quad\datasets";
libname Results  "&path1\analysis_sets\quad\models\results";
libname Exports  "&path1\analysis_sets\quad\exports";
 
options validvarname=v7 nodate center nonumber replace xsync noxwait nofmterr ls=96 mautosource 
sasautos=("&path2\macros");

data zallrxstudies;
 set SASdata.zallrxdata;
 study_num=allrx;
run;
proc sort data=zallrxstudies;
 by allrx;
run;
data allrxdata;
 set SASdata.allrxdata;
 study_num=allrx;
run;
data studydescrip;
 set SASdata.studydescrip;
 npatients=patients;
 nevents=n1;
 keep study_num study npatients nevents knot v4time1s pv4time1 v4time2s pv4time2 v4time3s pv4time3 mean_n_egfr 
      mean_max_visit_time mean_b_CKDegfr min_b_CKDegfr max_b_CKDegfr sum_ev_dx sum_ev_d sum_ev_x sum_ev_d2y pct_ev_dx 
      pct_ev_x pct_ev_d2y;
run;
/** Get baseline UP **/
data ddshort;
 set Master.fdac2_tx_allendpts;
 if b_ckdegfr=. then delete;
run;
data ddlong;
 set Master.fdac2_visits;
 if visit_time=. or visit_time <= 0 or fu_ckdegfr=. then delete;
run;
proc sort data=ddshort out=ddshort_unique(keep=new_id study_num) nodupkey;
 by new_id study_num;
run;
proc sort data=ddlong out=ddlong_unique(keep=new_id study_num) nodupkey;
 by new_id study_num;
run;
data unique_ids;
 merge ddshort_unique(in=in1) ddlong_unique(in=in2);
 by new_id study_num;
run;
proc sort data=ddshort;
 by new_id study_num;
run;
proc sort data=unique_ids;
 by new_id study_num;
run;
data dshort;
 merge ddshort(in=in1) unique_ids(in=in2);
 by new_id study_num;
 if in1 and in2;
run;
data base;
 set dshort;
 %include "&path2\macros\zupro.sas";
 zupro=zacr;
 zzupro=zacr;
 keep allrx zzupro;
run;
data base1;
 set base;
 rename allrx=study_num;
run;
proc means data=base1 median;
 var zzupro;
 class study_num;
 ods output summary=base_up(drop=nobs);
run;
/** CS **/
%macro cs(nstudies,out1);
data &out1;
 set %do s=1 %to &nstudies; 
 Results.cs&s 
 %end;;
 drop acr ce bounds quad trunc truncate bgfr log_acr acute_gfr;
run;
%mend;
%cs(1,cs_out);
data cs_out;
 set cs_out;
 rename corr=zpsi21_used pom=z_pom sp=z_sp prop=z_prop tech=ztech;
 model=3;
run;
data cs_out2;
 set cs_out;
 if z_prop="YES" then prop=1;else if z_prop="NO" then prop=0;
 if z_sp="YES" then sp=4;else if z_sp="NO" then sp=0;
 if z_pom="SS" then pom=1;else if z_pom="PA" then pom=2;else if z_pom="NO" then pom=3;else if z_pom="PO" then pom=4;
 if z_sp="YES" then surv=4;else if z_sp="NO" then surv=0;
 if zpsi21_used="YES" then psi21_used=1;else if zpsi21_used="NO" then psi21_used=0;
 if ztech="NRRIDG" then tech=1;else if ztech="DBLDOG" then tech=2;
 rename reason=cs_reason;
run;
proc sort data=studydescrip;
 by study;
run;
proc sort data=cs_out2;
 by study;
run;
data cs_out2;
 merge cs_out2 studydescrip(keep=study study_num knot);
 by study;
run;
proc sort data=cs_out2;
 by study model surv sp prop pom psi21_used;
run;
/** PE **/
%macro pe(nstudies,out1);
data &out1;
 set %do s=1 %to &nstudies; 
 Results.pe&s 
 %end;;
 drop acr ce bounds quad trunc truncate bgfr log_acr acute_gfr;
run;
%mend;
%pe(1,pe_out);
data pe_out;
 set pe_out;
 rename corr=zpsi21_used pom=z_pom sp=z_sp prop=z_prop tech=ztech;
 model=3;
run;
data pe_out;
 set pe_out;
 if z_prop="YES" then prop=1;else if z_prop="NO" then prop=0;
 if z_sp="YES" then sp=4;else if z_sp="NO" then sp=0;
 if z_pom="SS" then pom=1;else if z_pom="PA" then pom=2;else if z_pom="NO" then pom=3;else if z_pom="PO" then pom=4;
 if z_sp="YES" then surv=4;else if z_sp="NO" then surv=0;
 if zpsi21_used="YES" then psi21_used=1;else if zpsi21_used="NO" then psi21_used=0;
 if ztech="NRRIDG" then tech=1;else if ztech="DBLDOG" then tech=2;
run;
proc sort data=studydescrip;
 by study;
run;
proc sort data=pe_out;
 by study;
run;
data pe_out;
 merge pe_out studydescrip(keep=study study_num knot);
 by study;
run;
proc sort data=pe_out;
 by study model surv sp prop pom psi21_used;
run;
/** EST **/
%macro est(nstudies,out1);
data &out1;
 set %do s=1 %to &nstudies; 
 Results.est&s 
 %end;;
 drop acr ce bounds quad trunc truncate bgfr log_acr acute_gfr;
run;
%mend;
%est(1,est_out);
data est_out;
 set est_out;
 rename corr=zpsi21_used pom=z_pom sp=z_sp prop=z_prop tech=ztech;
 model=3;
run;
data est_out;
 set est_out;
 if z_prop="YES" then prop=1;else if z_prop="NO" then prop=0;
 if z_sp="YES" then sp=4;else if z_sp="NO" then sp=0;
 if z_pom="SS" then pom=1;else if z_pom="PA" then pom=2;else if z_pom="NO" then pom=3;else if z_pom="PO" then pom=4;
 if z_sp="YES" then surv=4;else if z_sp="NO" then surv=0;
 if zpsi21_used="YES" then psi21_used=1;else if zpsi21_used="NO" then psi21_used=0;
 if ztech="NRRIDG" then tech=1;else if ztech="DBLDOG" then tech=2;
run;
proc sort data=studydescrip;
 by study;
run;
proc sort data=est_out;
 by study;
run;
data est_out;
 merge est_out studydescrip(keep=study study_num knot);
 by study;
run;
proc sort data=est_out;
 by study model surv sp prop pom psi21_used;
run;
/** chronic slope for each arm **/
data pe_out1;
 set pe_out;
 if parameter in ("beta11" "beta12");
 est=12*estimate;
 if StandardError ne . then se=12*StandardError;else se=12*RobustStandardError;
 if parameter="beta11" then parameter="beta31";
 if parameter="beta12" then parameter="beta32";
 sem=12*StandardError;
 see=12*RobustStandardError;
 keep study model surv sp prop pom psi21_used parameter est se sem see;
run;
proc sort data=pe_out1;
 by study model surv sp prop pom psi21_used;
run;
proc transpose data=pe_out1 out=pe_out1a(drop=_name_) let suffix=_est;
 by study model surv sp prop pom psi21_used;
 var est;
 id parameter;
run;
proc transpose data=pe_out1 out=pe_out1b(drop=_name_) let suffix=_se;
 by study model surv sp prop pom psi21_used;
 var se;
 id parameter;
run;
proc transpose data=pe_out1 out=pe_out1c(drop=_name_) let suffix=_sem;
 by study model surv sp prop pom psi21_used;
 var sem;
 id parameter;
run;
proc transpose data=pe_out1 out=pe_out1d(drop=_name_) let suffix=_see;
 by study model surv sp prop pom psi21_used;
 var see;
 id parameter;
run;
/** treatment effect on chronic slope **/
data est_out1;
 set est_out;
 if label in ("beta12 - beta11");
 beta31_beta32_est=estimate;
 if StandardError ne . then beta31_beta32_se=StandardError;else beta31_beta32_se=RobustStandardError;
 beta31_beta32_sem=StandardError;
 beta31_beta32_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used beta31_beta32_est beta31_beta32_se beta31_beta32_sem beta31_beta32_see;
run;
proc sort data=pe_out1a;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=pe_out1b;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=pe_out1c;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=pe_out1d;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=est_out1;
 by study model surv sp prop pom psi21_used;
run;
data slopes_linear;
 merge pe_out1a pe_out1b pe_out1c pe_out1d est_out1;
 by study model surv sp prop pom psi21_used;
run;
data chronic_ratio;
 set est_out;
 if label in ("beta12/beta11");
 rbeta31_beta32_est=estimate;
 if StandardError ne . then rbeta31_beta32_se=StandardError;else rbeta31_beta32_se=RobustStandardError;
 rbeta31_beta32_sem=StandardError;
 rbeta31_beta32_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used rbeta31_beta32_est rbeta31_beta32_se rbeta31_beta32_sem rbeta31_beta32_see;
run;
proc sort data=chronic_ratio;
 by study model surv sp prop pom psi21_used;
run;
/** quadratic slope for each arm **/
data quad_out1;
 set pe_out;
 if parameter in ("beta21" "beta22");
 est=12*estimate;
 if StandardError ne . then se=12*StandardError;else se=12*RobustStandardError;
 if parameter="beta21" then parameter="beta21";
 if parameter="beta22" then parameter="beta22";
 sem=12*StandardError;
 see=12*RobustStandardError;
 keep study model surv sp prop pom psi21_used parameter est se sem see;
run;
proc sort data=quad_out1;
 by study model surv sp prop pom psi21_used;
run;
proc transpose data=quad_out1 out=quad_out1a(drop=_name_) let suffix=_est;
 by study model surv sp prop pom psi21_used;
 var est;
 id parameter;
run;
proc transpose data=quad_out1 out=quad_out1b(drop=_name_) let suffix=_se;
 by study model surv sp prop pom psi21_used;
 var se;
 id parameter;
run;
proc transpose data=quad_out1 out=quad_out1c(drop=_name_) let suffix=_sem;
 by study model surv sp prop pom psi21_used;
 var sem;
 id parameter;
run;
proc transpose data=quad_out1 out=quad_out1d(drop=_name_) let suffix=_see;
 by study model surv sp prop pom psi21_used;
 var see;
 id parameter;
run;
/** treatment effect on chronic slope **/
data quadx_out1;
 set est_out;
 if label in ("beta22 - beta21");
 beta21_beta22_est=12*estimate;
 if StandardError ne . then beta21_beta22_se=12*StandardError;else beta21_beta22_se=12*RobustStandardError;
 beta21_beta22_sem=12*StandardError;
 beta21_beta22_see=12*RobustStandardError;
 keep study model surv sp prop pom psi21_used beta21_beta22_est beta21_beta22_se beta21_beta22_sem beta21_beta22_see;
run;
proc sort data=quad_out1a;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=quad_out1b;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=quad_out1c;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=quad_out1d;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=quadx_out1;
 by study model surv sp prop pom psi21_used;
run;
data slopes_quad;
 merge quad_out1a quad_out1b quad_out1c quad_out1d quadx_out1;
 by study model surv sp prop pom psi21_used;
run;
/** Acute slope at the 4m knot **/
data acute4m;
 set est_out;
 if knot=4 and label in ("beta31 at t=4 Months" "beta32 at t=4 Months" "beta32 - beta31 at t=4 Months");
 if label in ("beta31 at t=4 Months")  then label="beta11";
 if label in ("beta32 at t=4 Months")  then label="beta12";
 if label in ("beta32 - beta31 at t=4 Months") then label="beta11_beta12";
 est=estimate;
 if StandardError ne . then se=StandardError;else se=RobustStandardError;
 sem=StandardError;
 see=RobustStandardError;
 keep study model surv sp prop pom psi21_used label est se sem see;
run;
proc sort data=acute4m;
 by study model surv sp prop pom psi21_used;
run;
proc transpose data=acute4m out=acute4ma(drop=_name_) let suffix=_est;
 by study model surv sp prop pom psi21_used;
 var est;
 id label;
run;
proc transpose data=acute4m out=acute4mb(drop=_name_) let suffix=_se;
 by study model surv sp prop pom psi21_used;
 var se;
 id label;
run;
proc transpose data=acute4m out=acute4mc(drop=_name_) let suffix=_sem;
 by study model surv sp prop pom psi21_used;
 var sem;
 id label;
run;
proc transpose data=acute4m out=acute4md(drop=_name_) let suffix=_see;
 by study model surv sp prop pom psi21_used;
 var see;
 id label;
run;
proc sort data=acute4ma;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute4mb;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute4mc;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute4md;
 by study model surv sp prop pom psi21_used;
run;
data acute4mx;
 merge acute4ma acute4mb acute4mc acute4md;
 by study model surv sp prop pom psi21_used;
run;
/** Acute slope at the 6m knot **/
data acute6m;
 set est_out;
 if knot=6 and label in ("beta31 at t=6 Months" "beta32 at t=6 Months" "beta32 - beta31 at t=6 Months");
 if label in ("beta31 at t=6 Months")  then label="beta11";
 if label in ("beta32 at t=6 Months")  then label="beta12";
 if label in ("beta32 - beta31 at t=6 Months") then label="beta11_beta12";
 est=estimate;
 if StandardError ne . then se=StandardError;else se=RobustStandardError;
 sem=StandardError;
 see=RobustStandardError;
 keep study model surv sp prop pom psi21_used label est se sem see;
run;
proc sort data=acute6m;
 by study model surv sp prop pom psi21_used;
run;
proc transpose data=acute6m out=acute6ma(drop=_name_) let suffix=_est;
 by study model surv sp prop pom psi21_used;
 var est;
 id label;
run;
proc transpose data=acute6m out=acute6mb(drop=_name_) let suffix=_se;
 by study model surv sp prop pom psi21_used;
 var se;
 id label;
run;
proc transpose data=acute6m out=acute6mc(drop=_name_) let suffix=_sem;
 by study model surv sp prop pom psi21_used;
 var sem;
 id label;
run;
proc transpose data=acute6m out=acute6md(drop=_name_) let suffix=_see;
 by study model surv sp prop pom psi21_used;
 var see;
 id label;
run;
proc sort data=acute6ma;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute6mb;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute6mc;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute6md;
 by study model surv sp prop pom psi21_used;
run;
data acute6mx;
 merge acute6ma acute6mb acute6mc acute6md;
 by study model surv sp prop pom psi21_used;
run;
/** Acute slope at the 8m knot **/
data acute8m;
 set est_out;
 if knot=8 and label in ("beta31 at t=8 Months" "beta32 at t=8 Months" "beta32 - beta31 at t=8 Months");
 if label in ("beta31 at t=8 Months")  then label="beta11";
 if label in ("beta32 at t=8 Months")  then label="beta12";
 if label in ("beta32 - beta31 at t=8 Months") then label="beta11_beta12";
 est=estimate;
 if StandardError ne . then se=StandardError;else se=RobustStandardError;
 sem=StandardError;
 see=RobustStandardError;
 keep study model surv sp prop pom psi21_used label est se sem see;
run;
proc sort data=acute8m;
 by study model surv sp prop pom psi21_used;
run;
proc transpose data=acute8m out=acute8ma(drop=_name_) let suffix=_est;
 by study model surv sp prop pom psi21_used;
 var est;
 id label;
run;
proc transpose data=acute8m out=acute8mb(drop=_name_) let suffix=_se;
 by study model surv sp prop pom psi21_used;
 var se;
 id label;
run;
proc transpose data=acute8m out=acute8mc(drop=_name_) let suffix=_sem;
 by study model surv sp prop pom psi21_used;
 var sem;
 id label;
run;
proc transpose data=acute8m out=acute8md(drop=_name_) let suffix=_see;
 by study model surv sp prop pom psi21_used;
 var see;
 id label;
run;
proc sort data=acute8ma;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute8mb;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute8mc;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute8md;
 by study model surv sp prop pom psi21_used;
run;
data acute8mx;
 merge acute8ma acute8mb acute8mc acute8md;
 by study model surv sp prop pom psi21_used;
run;
data acute;
 set acute4mx acute6mx acute8mx;
run;
/** Acute slope at 3 months **/
data acute3m;
 set est_out;
 if label in ("beta31 at t=3 Months" "beta32 at t=3 Months" "beta32 - beta31 at t=3 Months");
 if label in ("beta31 at t=3 Months")  then label="zbeta11";
 if label in ("beta32 at t=3 Months")  then label="zbeta12";
 if label in ("beta32 - beta31 at t=3 Months") then label="zbeta11_beta12";
 est=estimate;
 if StandardError ne . then se=StandardError;else se=RobustStandardError;
 sem=StandardError;
 see=RobustStandardError;
 keep study model surv sp prop pom psi21_used label est se sem see;
run;
proc sort data=acute3m;
 by study model surv sp prop pom psi21_used;
run;
proc transpose data=acute3m out=acute3ma(drop=_name_) let suffix=_est;
 by study model surv sp prop pom psi21_used;
 var est;
 id label;
run;
proc transpose data=acute3m out=acute3mb(drop=_name_) let suffix=_se;
 by study model surv sp prop pom psi21_used;
 var se;
 id label;
run;
proc transpose data=acute3m out=acute3mc(drop=_name_) let suffix=_sem;
 by study model surv sp prop pom psi21_used;
 var sem;
 id label;
run;
proc transpose data=acute3m out=acute3md(drop=_name_) let suffix=_see;
 by study model surv sp prop pom psi21_used;
 var see;
 id label;
run;
proc sort data=acute3ma;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute3mb;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute3mc;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute3md;
 by study model surv sp prop pom psi21_used;
run;
data acute3;
 merge acute3ma acute3mb acute3mc acute3md;
 by study model surv sp prop pom psi21_used;
run;
/** Merge slopes together **/
proc sort data=acute3;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=acute;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=slopes_linear;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=slopes_quad;
 by study model surv sp prop pom psi21_used;
run;
data all_slopes;
 merge acute3 acute slopes_linear slopes_quad;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=all_slopes;
 by study model surv sp prop pom psi21_used;
run;
/** Theta **/
data theta;
 set pe_out;
 if parameter in ("theta");
 theta_est=estimate;
 if StandardError ne . then theta_se=StandardError;else theta_se=RobustStandardError;
 theta_sem=StandardError;
 theta_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used theta_est theta_se theta_sem theta_see;
run;
/** Kappa **/
data kappa0;
 set pe_out;
 if parameter in ("kappa");
run;
data kappa;
 set kappa0;
 kappa_est=estimate;
 if StandardError ne . then kappa_se=StandardError;else kappa_se=RobustStandardError;
 kappa_sem=StandardError;
 kappa_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used kappa_est kappa_se kappa_sem kappa_see;
run;
proc sort data=kappa;
 by study model surv sp prop pom psi21_used;
run;
/** Sigma **/
data sigma;
 set pe_out;
 if parameter in ("sigma");
 sigma_est=estimate;
 if StandardError ne . then sigma_se=StandardError;else sigma_se=RobustStandardError;
 sigma_sem=StandardError;
 sigma_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used sigma_est sigma_se sigma_sem sigma_see;
run;
proc sort data=sigma;
 by study model surv sp prop pom psi21_used;
run;
/** psi11 **/
data psi11;
 set pe_out;
 if parameter in ("psi11");
 psi11_est=estimate;
 if StandardError ne . then psi11_se=StandardError;else psi11_se=RobustStandardError;
 psi11_sem=StandardError;
 psi11_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used psi11_est psi11_se psi11_sem psi11_see;
run;
proc sort data=psi11;
 by study model surv sp prop pom psi21_used;
run;
/** psi22 **/
data psi22;
 set pe_out;
 if parameter in ("psi22");
 psi22_est=estimate;
 if StandardError ne . then psi22_se=StandardError;else psi22_se=RobustStandardError;
 psi22_sem=StandardError;
 psi22_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used psi22_est psi22_se psi22_sem psi22_see;
run;
proc sort data=psi22;
 by study model surv sp prop pom psi21_used;
run;
/** psi21 **/
data psi21;
 set pe_out;
 if parameter in ("psi21");
 psi21_est=estimate;
 if StandardError ne . then psi21_se=StandardError;else psi21_se=RobustStandardError;
 psi21_sem=StandardError;
 psi21_see=RobustStandardError;
 keep study model surv sp prop pom psi21_used psi21_est psi21_se psi21_sem psi21_see;
run;
proc sort data=psi21;
 by study model surv sp prop pom psi21_used;
run;
/** Put all data together **/
proc sort data=all_slopes;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=theta;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=kappa;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=sigma;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=psi11;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=psi22;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=psi21;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=cs_out2;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=chronic_ratio;
 by study model surv sp prop pom psi21_used;
run;
data all0;
 merge chronic_ratio all_slopes theta kappa sigma psi11 psi22 psi21 cs_out2;
 by study model surv sp prop pom psi21_used;
run;
proc sort data=all0;
 by study;
run;
proc sort data=studydescrip;
 by study;
run;
data all0;
 merge all0(in=in1) studydescrip;
 by study;
 if in1;
run;
proc sort data=all0;
 by study_num;
run;
proc sort data=allrxdata;
 by study_num;
run;
proc sort data=base_up;
 by study_num;
run;
data all_models_t99;
 merge all0(in=in1) allrxdata base_up;
 by study_num;
 if in1;
run;
proc sort data=zallrxstudies;
 by study_num;
run;
proc sort data=all_models_t99;
 by study_num;
run;
data all_models_t99;
 merge all_models_t99(in=in1) zallrxstudies;
 by study_num;
 if in1;
run;
data xzall_models_t99;
 length study model surv sp prop pom psi21_used tech 
        zbeta11_est zbeta11_se zbeta11_sem zbeta11_see zbeta12_est zbeta12_se zbeta12_sem zbeta12_see zbeta11_beta12_est zbeta11_beta12_se zbeta11_beta12_sem zbeta11_beta12_see
        beta11_est beta11_se beta11_sem beta11_see beta12_est beta12_se beta12_sem beta12_see beta11_beta12_est beta11_beta12_se beta11_beta12_sem beta11_beta12_see
        beta31_est beta31_se beta31_sem beta31_see beta32_est beta32_se beta32_sem beta32_see beta31_beta32_est	beta31_beta32_se beta31_beta32_sem beta31_beta32_see rbeta31_beta32_est rbeta31_beta32_se rbeta31_beta32_sem rbeta31_beta32_see
		beta21_est beta21_se beta21_sem beta21_see beta22_est beta22_se beta22_sem beta22_see beta21_beta22_est	beta21_beta22_se beta21_beta22_sem beta21_beta22_see
        kappa_est kappa_se kappa_sem kappa_see theta_est theta_se theta_sem theta_see sigma_est sigma_se sigma_sem sigma_see psi11_est psi11_se psi11_sem psi11_see psi22_est psi22_se psi22_sem psi22_see psi21_est psi21_se psi21_sem psi21_see 8.;
 set all_models_t99;
 if study=. then delete;
run;
proc sort data=xzall_models_t99;
 by zallrx model surv sp prop;
run;
%zexportcsv(xzall_models_t99,nfirstmodelinseqperstudyt99,&path1\analysis_sets\quad\datasets);
data SASdata.nfirstmodelinseqperstudyt99;
 set xzall_models_t99;
run;
%zexportcsv(xzall_models_t99,nfirstmodelinseqperstudyt99,&path1\analysis_sets\quad\exports);
data Exports.nfirstmodelinseqperstudyt99;
 set xzall_models_t99;
run;

