%macro coxdata1(data,eventfile,out);
proc datasets nolist;
 delete out1 tm0 t1;
run;
quit;
data out1;
 set &data;
 event=0;
 timeevent=0;
 eventnumber=0;
 keep new_id allrx t_assign event timeevent eventnumber combo ztrt1 ztrt2;
run;
%let eventcount=%numwords(&eventcounter);
%do aa1=1 %to &eventcount;
%let eventnumber=%scan(&eventcounter,&aa1,' ');
proc datasets nolist;
 delete tm0 t1;
run;
quit;
data tm0;
 set &eventfile;
 if eventnumber=&eventnumber;
run;
proc sql noprint;
  select eventx,timex into :event,:time
  from tm0;
quit;
data t1;
 set &data;
 event=&event;
 timeevent=&time;
 eventnumber=&eventnumber;
 keep new_id allrx t_assign event timeevent eventnumber combo ztrt1 ztrt2;
run;
data out1;
 set out1 t1;
run;
proc datasets nolist;
 delete tm0 t1;
run;
quit;
%end;
data &out;
 set out1;
 if eventnumber=0 then delete;
run;
proc datasets nolist;
 delete out1 tm0 t1;
run;
quit;
%mend;