%macro coxps1(data,byvar,time,event,strata,cov,varlist,out);
ods listing close;
proc datasets nolist;
delete temp cs pe pe_cs convergencestatus freqs freqs1 freqs2;
run;
quit;
options nonotes nomprint nomlogic nosymbolgen;
data temp;
 set &data;
 if &cov=. then delete; 
 /*%if %length(&varlist)>0 %then %do;
 if &varlist=. then delete;/** assume one covariate to adjust for **
 %end;*/
run;
proc sort data=temp;
 by &byvar;
run;
proc phreg data=temp;
 model &time*&event(0)=&cov &varlist/rl;
 strata &strata;
 ods output censoredsummary=cs(keep=&byvar &strata total event);
 ods output parameterestimates=pe(keep=&byvar parameter df estimate stderr chisq probchisq hazardratio hrlowercl hruppercl);
 ods output convergencestatus=convergencestatus;
 by &byvar;
run;
proc sort data=pe;
 by &byvar;
run;
data cs;
 set cs;
 if compress(&strata)="";
 drop &strata;
run;
proc sort data=cs;
 by &byvar;
run;
proc sort data=convergencestatus;
 by &byvar;
run;
data &out;
 merge cs pe convergencestatus;
 by &byvar;
run;
 data &out;
 set &out;
 hr_pct=100*(hazardratio-1);
 hrlowercl_pct=100*(hrlowercl-1);
 hruppercl5_pct=100*(hruppercl-1);
run;
proc datasets nolist;
delete temp cs pe pe_cs convergencestatus;
run;
quit;
proc sort data=&out;
 by &byvar;
run;
ods listing;
options notes mprint symbolgen mlogic;
%mend;

