%macro large(data,n1,n2,out);
proc datasets nolist;
 delete temp temp1 sizeofstudies sizeofstudies1 large large1 large2;
run;
quit;
data temp;
 set &data;
run;
proc sort data=temp out=sizeofstudies nodupkey;
 by study new_id;
run;
proc sql noprint;
 create table sizeofstudies1 as
 select study, count(*) as count
 from sizeofstudies
 group by study;
quit;
data sizeofstudies2;
 set sizeofstudies1;
 if count > &n1;
run;
proc sql noprint;
select study into :studiesid separated by ' ' from sizeofstudies2;
quit;
data large;
 set temp;
 if study in (&studiesid);
 keep study subject t_assign new_id;
run;
proc sort data=large out=large1 nodupkey;
 by study subject;
run;
proc sort data=large1;
 by study t_assign;
run;
proc surveyselect data=large1 method=srs n=&n2 out=large2 seed=1234;
 strata study t_assign;
run;
%if %obsnumber(large2)>0 %then %do;
data large2;
 set large2;
 sampled=1;
 keep study new_id sampled;
run;
proc sort data=large2;
 by study new_id;
run;
proc sort data=temp;
 by study new_id;
run;
data temp1;
 merge temp(in=in1) large2(in=in2);
 by study new_id;
 if in1;
run;
data &out;
 set temp1;
 if study in (&studiesid) and sampled=. then delete;
run;
proc sort data=&out; 
 by study subject Month; 
run;
proc sort data=&out out=u1 nodupkey;
 by study new_id;
run;
%end;
%else %do;
data &out;
 set temp;
run;
proc sort data=&out; 
 by study subject Month; 
run;
proc sort data=&out out=u1 nodupkey;
 by study new_id;
run;
%end;
proc datasets nolist;
 delete temp temp1 sizeofstudies sizeofstudies1 large large1 large2;
run;
quit;
%mend;