if compress(UP_MeasureToUse)="PER" then do;
	zupro=base_24_upro_tot*1;
	 zacr=base_24_upro_tot/1.67;
 end;
if compress(UP_MeasureToUse)="AER" then do;
	zupro=base_24_ualb_tot*1;
     zacr=base_24_ualb_tot*1;
 end;
if compress(UP_MeasureToUse)="PCR" then do;
	zupro=base_24_upro_rat*1;
   	 zacr=base_24_upro_rat/1.67;
 end;
if compress(UP_MeasureToUse)="ACR" then do;
	zupro=base_24_ualb_rat*1;
     zacr=base_24_ualb_rat*1;
 end;
if compress(UP_MeasureToUse)="SPCR" then do;
	zupro=base_spot_upro_rat*1; 
 	 zacr=base_spot_upro_rat/1.67;  
 end;
if compress(UP_MeasureToUse)="SACR" then do;
	zupro=base_spot_ualb_rat*1; 
     zacr=base_spot_ualb_rat*1; 
 end;